### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by johnbent** [Seagate/s3bench#9]
@TechWriter-Mayur , can you please add the badges here?  Also, can you work with @mukul-seagate11 to get codacy working if it isn't yet?

**Comment by mukul-seagate11** [comment]
@johnbent, added the Codacy badge via [Add a Codacy badge to README.md by codacy-badger · Pull Request #10 · Seagate/s3bench (github.com)](https://github.com/Seagate/s3bench/pull/10/files) through s3bench is a forked repo

**Comment by johnbent** [comment]
![](https://user-images.githubusercontent.com/2047294/107067189-2b109c00-679c-11eb-9e97-17e5a8e5af3d.png)

*   [ ] remove the broken Codacy Badge
*    [ ]  add youtube badge
*    [ ]  add slack badge
*    [ ]  add license badge

**Comment by TechWriter-Mayur** [comment]
> 
> 
> ![](https://user-images.githubusercontent.com/2047294/107067189-2b109c00-679c-11eb-9e97-17e5a8e5af3d.png)
> 
>     * [ ]  remove the broken Codacy Badge
> 
>     * [ ]   add youtube badge
> 
>     * [ ]   add slack badge
> 
>     * [ ]   add license badge

Created the PR #11 for the same.
